name: pymandel

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deploy dependencies
        run: |
          pip install .[deploy]
      - name: Install test dependencies
        run: |
          pip install .[test]
      - name: Install code dependencies
        run: |
          pip install .
      - name: Lint with pylint
        run: |
          pylint -E src/pmandel
      - name: Security vulnerability analysis with bandit
        run: |
          bandit -c pyproject.toml -r .
      - name: Test with pytest
        run: |
          pytest
